### Integer Indexes

In [3]:
import pandas as pd
import numpy as np

In [5]:
ser = pd.Series(np.arange(3.)) 
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [6]:
ser[-1] 

KeyError: -1

In [7]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

ser2[-1]

2.0

In [8]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [10]:
ser.iloc[-1] #iloc : for intergers, loc : for labes

2.0

## Arithmetric and Data Alignment

In [11]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], 
               index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], 
               index=['a', 'c', 'e', 'f', 'g'])

In [12]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [13]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [14]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [16]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [17]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [18]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [19]:
df1 + df2 # 겹치는 row나 column이 하나도 없으면 모두 NA

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [20]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                   columns=list('abcde'))

In [21]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [22]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [23]:
df2.loc[1,'b'] =np.nan

df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [24]:
df1 + df2 #기존에 NA가 위치했던 자리에는 overlap되지않음

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [26]:
df1.add(df2, fill_value = 0) 
#add 메소드 써서 df2의 na 0으로 채우기

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### Operations between DataFrame and Series

In [27]:
arr = np.arange(12.).reshape((3, 4))

arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
arr[0]

array([0., 1., 2., 3.])

In [29]:
arr - arr[0] #subtract for each row

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [30]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon']) 

series = frame.iloc[0]

frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [31]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [32]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [33]:
series3 = frame['d']

series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [34]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

In [35]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon']) 

frame

b         d         e
Utah    0.348567 -0.798744 -0.060870
Ohio   -0.371146 -0.531169  1.429084
Texas  -0.270060 -2.115290  0.157138
Oregon  1.547145 -0.000669  1.242917

In [36]:
np.abs(frame)

b         d         e
Utah    0.348567  0.798744  0.060870
Ohio    0.371146  0.531169  1.429084
Texas   0.270060  2.115290  0.157138
Oregon  1.547145  0.000669  1.242917

In [39]:
f = lambda x: x.max() - x.min()

In [40]:
frame.apply(f) #axis = 'columns'로 주면 열에 대해

b    1.918291
d    2.114621
e    1.489954
dtype: float64

In [41]:
format = lambda x : '%.2f' % x

In [47]:
frame.applymap(format)

#The reason for the name applymap is 
#that Series has a map method 
#for applying an element-wise function

b      d      e
Utah     0.35  -0.80  -0.06
Ohio    -0.37  -0.53   1.43
Texas   -0.27  -2.12   0.16
Oregon   1.55  -0.00   1.24

## Sorting and Ranking

In [48]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c']) 

obj.sort_index() # 인덱스 순서대로

a    1
b    2
c    3
d    0
dtype: int64

In [50]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c']) 
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [54]:
frame.sort_index(axis=1) 
#ascending=False로 두면 역순으로 

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [55]:
obj = pd.Series([4, 7, -3, 2])

obj.sort_values()#NA있으면 맨 끝으로 감

2   -3
3    2
0    4
1    7
dtype: int64

In [58]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]}) 

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [59]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [60]:
frame.sort_values(by = ['a','b']) 
#multiple columns에 대한 sort

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [61]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4]) 
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [62]:
obj.rank() 
#순위 매기기. 동순위는 평균순위로
#method = 'first' 설정하면 동순위라도 먼저 관측것 우선

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [63]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 
                      'c': [-2, 5, 8, -2.5]}) 

frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [64]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Axis Indexse with Duplicate Labels

In [65]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c']) 

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [66]:
obj.index.is_unique

False

In [67]:
obj['a']

a    0
a    1
dtype: int64

In [68]:
obj['c']

4

In [69]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b']) 

df

0         1         2
a -1.043731  0.294586 -1.039780
a  1.756549 -1.255062 -0.028656
b  2.414678  0.661312  0.683006
b -1.347854 -0.153195  1.752029

In [70]:
df.loc['b']

0         1         2
b  2.414678  0.661312  0.683006
b -1.347854 -0.153195  1.752029

# 5.3 Summarizing and Computing Descriptive Statistics

In [71]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                   [np.nan, np.nan], [0.75, -1.3]], 
                  index=['a', 'b', 'c', 'd'], 
                  columns=['one', 'two']) 
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [72]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [73]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [74]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [75]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [77]:
df.idxmax()

one    b
two    d
dtype: object

In [79]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [80]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [81]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4) 

obj.describe() #for non-numeric data

count     16
unique     3
top        a
freq       8
dtype: object

## Correlation and Covariance

In [4]:
import pandas_datareader.data as web 
all_data = {ticker: web.get_data_yahoo(ticker) 
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']} 
price = pd.DataFrame({ticker: data['Adj Close'] 
                      for ticker, data in all_data.items()}) 
volume = pd.DataFrame({ticker: data['Volume'] 
                       for ticker, data in all_data.items()})

In [5]:
returns = price.pct_change()

In [6]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-06-27  0.000000  0.005209 -0.010497 -0.016159
2022-06-28 -0.029790 -0.006583 -0.031749 -0.034736
2022-06-29  0.013024 -0.008107  0.014738 -0.002798
2022-06-30 -0.018028  0.003411 -0.013179 -0.025691
2022-07-01  0.016164 -0.000496  0.010707 -0.002665

In [7]:
returns['MSFT'].corr(returns['IBM'])

0.48298043241179855

In [8]:
returns['MSFT'].cov(returns['IBM'])

0.0001526365761612835

In [9]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.437978  0.758414  0.683263
IBM   0.437978  1.000000  0.482980  0.457513
MSFT  0.758414  0.482980  1.000000  0.785918
GOOG  0.683263  0.457513  0.785918  1.000000

In [10]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000408  0.000151  0.000284  0.000253
IBM   0.000151  0.000291  0.000153  0.000143
MSFT  0.000284  0.000153  0.000343  0.000267
GOOG  0.000253  0.000143  0.000267  0.000337

In [11]:
returns.corrwith(returns.IBM)

AAPL    0.437978
IBM     1.000000
MSFT    0.482980
GOOG    0.457513
dtype: float64

## Unique Values, Value Counts, and Membership

In [12]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

uniques = obj.unique()

uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [13]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [15]:
mask = obj.isin(['b', 'c'])

mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [16]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [17]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a']) 
unique_vals = pd.Series(['c', 'b', 'a']) 
pd.Index(unique_vals).get_indexer(to_match)
#unique value에 대한 index로 전체 data에 대한 index

array([0, 2, 1, 1, 0, 2])

In [18]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 
                     'Qu2': [2, 3, 1, 2, 3], 
                     'Qu3': [1, 5, 2, 4, 4]}) 
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [19]:
result = data.apply(pd.value_counts).fillna(0) 

result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0